### ISSUE TITLE
Register pg_service configuration as a QGIS connection in the user profile

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-pg-service-parser-plugin#50] opened 2024-09-25 15:24 UTC
After defining a pg_service configuration, I can set it as a QGIS connexion in my user profile with a simple button :

Example :

![image](https://github.com/user-attachments/assets/00fa281c-cdc7-4486-917c-4613603c74a4)

Can create :

![image](https://github.com/user-attachments/assets/e4e236ac-178e-4309-95c2-4084eb3db8c6)

**Comment by ponceta** [comment] 2024-09-25 15:26
https://github.com/opengisch/qgis-pg-service-parser-plugin/pull/39

Looks like it is already on the way to be a feature!

**Comment by gacarrillor** [comment] 2024-10-04 23:13
Thanks for the suggestion!

Closing as a duplicate of #38

**Closed by gacarrillor** 2024-10-04 23:13 UTC
Labels: duplicate
